#!/usr/bin/env bash
# scripts/e2e/setup-local-supabase.sh — stand up the LOCAL Supabase stack for the
# E2E harness and write .env.e2e.local. Idempotent. LOCAL / TEST ONLY.
#
# What it does:
#   1. `supabase start` (if not already running) — a full local stack: real GoTrue
#      (auth) + Postgres with the project migrations applied. Mirrors production
#      shape (one DB owns both the `auth` and `public` schemas).
#   2. Provisions `e2e_auth` — a LOGIN role that is a member of `authenticated`
#      (so it inherits the RLS grants) but is NOT a superuser and does NOT bypass
#      RLS. This is the app's USER_DATABASE_URL role locally (Supabase's own
#      `authenticated` role is reserved/NOLOGIN and can't be used directly).
#   3. Writes .env.e2e.local (gitignored) with the loopback endpoints/keys.
#
# The keys emitted here are the well-known `supabase start` demo keys — public,
# loopback-only, never production secrets. The default-deny supabase-guard
# (lib/testing/supabase-guard.ts) independently refuses any non-loopback target.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
export PATH="$HOME/.npm-global/bin:$PATH"

# Local-only dummy password for the RLS role (same spirit as the local-db auth stub).
E2E_AUTH_PW="e2e_local_authenticated"

echo "→ ensuring local Supabase stack is up"
if ! supabase status >/dev/null 2>&1; then
  supabase start
else
  echo "  (already running)"
fi

# Load endpoints/keys as shell vars (ANON_KEY, API_URL, DB_URL, SERVICE_ROLE_KEY...).
eval "$(supabase status -o env)"
: "${API_URL:?supabase status did not report API_URL}"
: "${ANON_KEY:?}"
: "${SERVICE_ROLE_KEY:?}"
: "${DB_URL:?}"

# Belt-and-braces: this bootstrap must only ever touch a loopback stack.
case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*|http://0.0.0.0:*) ;;
  *) echo "REFUSING: API_URL ($API_URL) is not loopback" >&2; exit 1 ;;
esac

echo "→ provisioning RLS-subject login role (e2e_auth)"
CID="$(docker ps --format '{{.Names}}' | grep -E '^supabase_db_' | head -1)"
: "${CID:?supabase db container not found}"
docker exec -i "$CID" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='e2e_auth') THEN
    CREATE ROLE e2e_auth LOGIN PASSWORD '${E2E_AUTH_PW}'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;
  ELSE
    ALTER ROLE e2e_auth WITH LOGIN PASSWORD '${E2E_AUTH_PW}';
  END IF;
END \$\$;
GRANT authenticated TO e2e_auth;
GRANT CONNECT ON DATABASE postgres TO e2e_auth;
SQL

USER_DB_URL="postgresql://e2e_auth:${E2E_AUTH_PW}@127.0.0.1:54322/postgres"

echo "→ writing .env.e2e.local"
cat > .env.e2e.local <<EOF
# Generated by scripts/e2e/setup-local-supabase.sh — LOCAL/TEST ONLY, gitignored.
# Values are the well-known local \`supabase start\` demo keys (loopback-only).
SUPABASE_URL=${API_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DATABASE_URL=${DB_URL}
USER_DATABASE_URL=${USER_DB_URL}
NEXT_PUBLIC_APP_ENV=test
NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3000
E2E_BASE_URL=http://127.0.0.1:3000
EOF

echo "✔ E2E local Supabase ready (target ${API_URL}). Now run: npm run build && bash scripts/e2e/run-e2e.sh"
