#!/usr/bin/env bash
# scripts/e2e/setup-local-supabase.sh — stand up the LOCAL Supabase stack for the
# E2E harness and write .env.e2e.local. Idempotent. LOCAL / TEST ONLY.
#
# What it does:
#   1. `supabase start` (if not already running) — a full local stack: real GoTrue
#      (auth) + Postgres with the project migrations applied. Mirrors production
#      shape (one DB owns both the `auth` and `public` schemas).
#   2. Provisions `e2e_auth` — a LOGIN role that is a member of `authenticated`
#      (so it inherits the RLS grants) but is NOT a superuser and does NOT bypass
#      RLS. This is the app's USER_DATABASE_URL role locally (Supabase's own
#      `authenticated` role is reserved/NOLOGIN and can't be used directly).
#   3. Writes .env.e2e.local (gitignored) with the loopback endpoints/keys.
#
# The keys emitted here are the well-known `supabase start` demo keys — public,
# loopback-only, never production secrets. The default-deny supabase-guard
# (lib/testing/supabase-guard.ts) independently refuses any non-loopback target.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
export PATH="$HOME/.npm-global/bin:$PATH"

# Local-only dummy password for the RLS role (same spirit as the local-db auth stub).
E2E_AUTH_PW="e2e_local_authenticated"

# A DECOY for the retired admin shared secret. The admin console accepted ADMIN_DASHBOARD_TOKEN
# (as `?token=` / `x-admin-token`) until 2026-09-24; that code is gone and the app no longer reads
# the variable at all. It is still provisioned into .env.e2e.local ON PURPOSE, so the served app
# runs in the dangerous configuration: tests/e2e/a11y/routes.anon.a11y.spec.ts then presents this
# exact value to every admin route and asserts a 404, which proves on a real `next start` build —
# not only in unit tests — that setting the variable re-opens nothing.
# The admin a11y sweep itself now signs in for real (routes.authed.a11y.spec.ts, via the seeded
# local test user). Fixed, PUBLIC, loopback-only value — NOT a production secret.
E2E_ADMIN_TOKEN="e2e-local-admin-dashboard-token"

# On the shared dev server, `supabase start` publishes the stack's ports on 0.0.0.0 (Docker's
# default), which bypasses the host firewall and exposes the demo-password Postgres to the internet
# (this happened: incident 2026-09-25). The server provides a wrapper that starts the stack and
# immediately rebinds every published port to 127.0.0.1. Use it when present; elsewhere (CI runners,
# laptops) fall back to plain `supabase start`.
SAFE_START=/opt/projects/crhq-satellite/documents/security/supabase-start-safe.sh

echo "→ ensuring local Supabase stack is up"
if ! supabase status >/dev/null 2>&1; then
  if [ -f "$SAFE_START" ]; then
    bash "$SAFE_START" "$ROOT"
  else
    supabase start
  fi
else
  echo "  (already running)"
fi

# Load endpoints/keys as shell vars (ANON_KEY, API_URL, DB_URL, SERVICE_ROLE_KEY...).
eval "$(supabase status -o env)"
: "${API_URL:?supabase status did not report API_URL}"
: "${ANON_KEY:?}"
: "${SERVICE_ROLE_KEY:?}"
: "${DB_URL:?}"

# Belt-and-braces: this bootstrap must only ever touch a loopback stack.
case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*|http://0.0.0.0:*) ;;
  *) echo "REFUSING: API_URL ($API_URL) is not loopback" >&2; exit 1 ;;
esac

echo "→ provisioning RLS-subject login role (e2e_auth)"
CID="$(docker ps --format '{{.Names}}' | grep -E '^supabase_db_' | head -1)"
: "${CID:?supabase db container not found}"
docker exec -i "$CID" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='e2e_auth') THEN
    CREATE ROLE e2e_auth LOGIN PASSWORD '${E2E_AUTH_PW}'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS INHERIT;
  ELSE
    ALTER ROLE e2e_auth WITH LOGIN PASSWORD '${E2E_AUTH_PW}';
  END IF;
END \$\$;
GRANT authenticated TO e2e_auth;
GRANT CONNECT ON DATABASE postgres TO e2e_auth;
SQL

USER_DB_URL="postgresql://e2e_auth:${E2E_AUTH_PW}@127.0.0.1:54322/postgres"

echo "→ writing .env.e2e.local"
cat > .env.e2e.local <<EOF
# Generated by scripts/e2e/setup-local-supabase.sh — LOCAL/TEST ONLY, gitignored.
# Values are the well-known local \`supabase start\` demo keys (loopback-only).
SUPABASE_URL=${API_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DATABASE_URL=${DB_URL}
USER_DATABASE_URL=${USER_DB_URL}
NEXT_PUBLIC_APP_ENV=test
NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3000
E2E_BASE_URL=http://127.0.0.1:3000
# DECOY (see E2E_ADMIN_TOKEN above): the app no longer reads this; the anon a11y spec asserts that
# presenting it to /admin/* still 404s. Sourced by run-e2e.sh into BOTH the app and Playwright.
ADMIN_DASHBOARD_TOKEN=${E2E_ADMIN_TOKEN}
# The SMS signup release switch (lib/sms/config.ts \`smsSignupEnabled()\`). It DEFAULTS TO FALSE,
# which means the default state of a local E2E run was: /sms/start 404s, the home page correctly
# renders no signup action (AC-12), and every spec that needs the enabled branch has nothing to
# look at. Two specs need it and neither skips silently —
# tests/e2e/public/sms-cta-analytics.public.spec.ts (M1 T1.6) asserts the CTA is present with a
# message naming this variable, and tests/e2e/public/address-integrity.public.spec.ts (M4 T4.3)
# asserts /sms/start's status against it. Provisioned here because run-e2e.sh sources this file before starting BOTH the app server
# and the Playwright process, so the flag the specs expect is the flag the app is running with.
# Flip it to any other value to exercise the fail-safe (404 / no-action) branch instead.
SMS_SIGNUP_ENABLED=true
EOF

echo "✔ E2E local Supabase ready (target ${API_URL}). Now run: npm run build && bash scripts/e2e/run-e2e.sh"
