// scripts/incident/cleanup-2026-09-21-fixture-pollution.ts — OPERATOR TOOL, one-off remediation
// for the 2026-09-21 incident in which a full `vitest --project db` run executed against the
// PRODUCTION database (18:40:01–18:53:36Z), minting test fixtures into live tables.
//
//   KF_CLEANUP_TARGET_URL='postgres://…' bash scripts/incident/cleanup-2026-09-21-fixture-pollution.sh
//
// ═══ WHY THIS READS KF_CLEANUP_TARGET_URL AND NOT DATABASE_URL ═══
// Same convention as scripts/snapshot/export.sh, and for a sharper reason here: the incident this
// script cleans up was caused by a shell whose DATABASE_URL pointed at production. A remediation
// tool that read DATABASE_URL would be reachable by exactly the environment that caused the
// damage, and would run silently in any dev shell. Its own variable means running it is always a
// deliberate act, and it is invisible to `npm test`, `npm run dev` and CI.
//
// ═══ SAFETY MODEL: IDENTITY, NOT INFERENCE ═══
// Nothing here is matched by date window, name pattern or family at run time. The target set is a
// REVIEWED MANIFEST OF EXPLICIT UUIDs (manifest-2026-09-21-fixture-pollution.json), generated by a
// read-only query and reviewed before use. At run time every id is re-verified against the
// family/name/created_at fingerprint recorded in the manifest, and ANY drift aborts the whole run.
// That matters because six of the polluted families — activenet, library_bibliocommons,
// perfectmind, venue_html, editorial_roundup, manual — are ALSO real production families. A
// family- or window-scoped DELETE would be a second incident. Every one of the 56 rows was
// independently attributed to the specific test file whose literal mints it (see ATTRIBUTION in
// the manifest's sibling notes); zero were unattributable.
//
// ═══ WHAT IT DELIBERATELY DOES NOT TOUCH ═══
//  • the 11 source rows whose occurrences the OPERATOR archived on the night (manifest
//    `leave_alone_source_ids`). Those are contained and reversible via `archived_at`; closing them
//    out is the Operator's call, not this script's. The run ABORTS if any of them is in the target
//    set, so the two sets can never overlap.
//  • the 16,561 REAL occurrences the test run flipped to 'stale'. That is a separate, larger
//    remediation with its own decision to make (let the real cadence re-check vs. restore prior
//    status), and it is NOT fixture cleanup. This script asserts that count is UNCHANGED across
//    its own transaction, so it cannot be blamed for, or hide, movement there.
//  • anything outside the manifest. Global invariants are asserted before and after: the number of
//    sources created outside the incident window, and the total occurrence/stale counts, must not
//    move by even one row.
//
// ═══ A TRAP FOR ANYONE VERIFYING THIS SCRIPT'S FLAG HANDLING ═══
// The precondition checks run BEFORE the commit/rollback decision, so against a database whose
// counts do not match the manifest this script exits 1 (ABORTED) no matter what flags you pass —
// which looks exactly like "half-confirmation returns 1" and hides the branch you meant to test.
// A reviewer measured precisely that and briefly concluded this script behaved differently from
// its siblings. To exercise flag handling you need a target whose preconditions PASS. With the
// rehearsal harness that means a bare `node reset-replica.cjs` and NOT seeding the dedup-followup
// fixtures first — those add 18 occurrences (31,979 → 31,997) and trip occ_total.
//
// ═══ DRY RUN IS THE DEFAULT ═══
// With no flags it does every verification and every DELETE inside a transaction, prints the exact
// row counts, and then ROLLS BACK. The printed plan is therefore not a prediction — it is the
// result of really executing it. Committing requires BOTH --commit and
// --yes-write-production, because a single flag is one typo or one shell-history arrow-up away.
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Pool, type PoolClient } from 'pg';
// Relative, not '@/': these scripts run under vite-node, which does not load the Vitest alias.
import { isLocalDatabaseHost, resolveEffectiveHost } from '../../lib/db/connection-host';
import { resolveSslFor } from './_ssl';

interface SourceRow { id: string; family: string; name: string; terms_status: string; created_at: string }
interface VenueRow { id: string; name: string; created_at: string }
interface Manifest {
  window: { from: string; to: string };
  containment_archived_at_floor: string;
  leave_alone_source_ids: string[];
  target_sources: SourceRow[];
  target_series_ids: string[];
  target_occurrence_ids: string[];
  fixture_venues: VenueRow[];
  orphan_profile_ids: string[];
  expected_dependent_counts: Record<string, number>;
  expected_preconditions: Record<string, number>;
}

function parseArgs(argv: string[]) {
  const flags = new Set<string>();
  let manifest = '';
  // Both `--key value` and `--key=value`. The `=` form was silently ignored, so `--manifest=path`
  // fell through to the DEFAULT manifest while looking honoured — a real footgun for a tool whose
  // entire safety model is "operate only on this reviewed list of ids".
  for (let i = 0; i < argv.length; i++) {
    const raw = argv[i];
    if (!raw.startsWith('--')) continue;
    const eq = raw.indexOf('=');
    const key = eq >= 0 ? raw.slice(0, eq) : raw;
    const inline = eq >= 0 ? raw.slice(eq + 1) : null;
    if (key === '--manifest') { manifest = inline !== null ? inline : (argv[++i] ?? ''); continue; }
    flags.add(key);
  }
  return {
    commit: flags.has('--commit'),
    confirmed: flags.has('--yes-write-production'),
    includeAdminFixtures: flags.has('--include-admin-fixtures'),
    includeVenues: !flags.has('--skip-venues'),
    // Resolved from cwd, not from argv[1]: the wrapper always cds to the repo root, and under
    // vite-node argv[1] is the vite-node binary rather than this file.
    manifestPath: manifest || join(process.cwd(), 'scripts/incident/manifest-2026-09-21-fixture-pollution.json'),
  };
}

class Abort extends Error {}
/** Every precondition failure routes through here so the message format is uniform and the
 *  transaction is always rolled back by the single catch in main(). */
function require_(cond: boolean, message: string): void {
  if (!cond) throw new Abort(message);
}

const log = (s: string) => process.stdout.write(`${s}\n`);
const count = async (c: PoolClient, sql: string, params: unknown[] = []): Promise<number> =>
  Number((await c.query<{ n: string }>(sql, params)).rows[0].n);

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const url = process.env.KF_CLEANUP_TARGET_URL;
  if (!url) {
    log('KF_CLEANUP_TARGET_URL is not set. Refusing to guess a target database.');
    process.exit(2);
  }
  if (!existsSync(args.manifestPath)) {
    log(`manifest not found: ${args.manifestPath}\nRun this from the repo root, or pass --manifest <path>.`);
    process.exit(2);
  }
  const m: Manifest = JSON.parse(readFileSync(args.manifestPath, 'utf8'));

  // ── Manifest self-consistency, before a connection is even opened ────────────────────────
  // These run OUTSIDE the transaction (there isn't one yet), so they need their own handler —
  // without it an Abort here escaped as an unhandled stack trace instead of a readable refusal.
  // Found by a tampered-manifest negative test, which is exactly the path a reviewer would use.
  const targetIds = m.target_sources.map((s) => s.id);
  try {
    require_(targetIds.length > 0, 'manifest has no target_sources — nothing to do');
    require_(new Set(targetIds).size === targetIds.length, 'manifest contains duplicate target source ids');
    const overlap = targetIds.filter((id) => m.leave_alone_source_ids.includes(id));
    require_(
      overlap.length === 0,
      `manifest overlap: ${overlap.length} target id(s) are ALSO leave_alone ids (${overlap
        .slice(0, 3)
        .join(', ')}${overlap.length > 3 ? ', …' : ''}) — the contained set and the delete set must be disjoint. Refusing.`
    );
    require_(
      new Set(m.target_series_ids).size === m.target_series_ids.length &&
        new Set(m.target_occurrence_ids).size === m.target_occurrence_ids.length,
      'manifest contains duplicate series/occurrence ids'
    );
  } catch (err) {
    log(`\n✖ ABORTED: ${(err as Error).message}\n  No database connection was opened.`);
    process.exit(1);
  }

  // TLS via the shared decision (./_ssl.ts). Disabling certificate verification on a PRODUCTION
  // SUPERUSER connection is not a defensible default, and `rejectUnauthorized: true` alone does not
  // work either — Supabase's chain is privately rooted. So: verify against a supplied CA, or refuse.
  const { ssl } = resolveSslFor(url);
  const pool = new Pool({ connectionString: url, ssl });
  const c = await pool.connect();
  let committed = false;
  try {
    await c.query('BEGIN');
    // The host the connection DECISION used, not `new URL(url).host` — they differ for a `?host=`
    // override or a hostless URL resolved through PGHOST, so the operator's pre-flight confirmation
    // could otherwise name a different database than the one actually dialed.
    const target = resolveEffectiveHost(url);
    const via = target.source === 'url' ? '' : ` (via ${target.source})`;
    log(`\n── target: ${target.host ?? '<unparseable>'}${via}  ·  mode: ${args.commit && args.confirmed ? 'COMMIT' : 'DRY RUN (rollback)'} ──\n`);

    // ── 1. Identity re-verification. Every id must still be the row the manifest fingerprinted.
    const live = (await c.query<SourceRow>(
      `SELECT id::text, family, name, terms_status, created_at::text FROM source WHERE id = ANY($1::uuid[])`,
      [targetIds]
    )).rows;
    require_(live.length === targetIds.length,
      `expected ${targetIds.length} target sources, found ${live.length} — the database does not match the manifest (already cleaned? wrong database?)`);
    const byId = new Map(live.map((r) => [r.id, r]));
    for (const want of m.target_sources) {
      const got = byId.get(want.id);
      require_(!!got, `target source ${want.id} is missing`);
      require_(got!.family === want.family && got!.name === want.name,
        `fingerprint drift on ${want.id}: manifest says ${want.family}/"${want.name}", database says ${got!.family}/"${got!.name}" — refusing`);
      require_(Date.parse(got!.created_at) === Date.parse(want.created_at),
        `created_at drift on ${want.id} — refusing`);
    }
    log(`✔ identity verified: ${live.length} fixture source rows match the manifest exactly`);

    // ═══ THE ID ARRAYS GET CHECKED TOO ═══
    // target_series_ids / target_occurrence_ids / fixture_venues were previously deleted on
    // manifest trust alone, while the docs claimed "every id is re-verified". Rather than soften
    // the claim, make it true: each id must still hang off the fixture graph (or, for venues,
    // still match its recorded name), so a manifest pointing at anything else cannot delete it.
    const missingVenues = m.fixture_venues.length - (await count(c,
      `SELECT count(*) n FROM venue WHERE id = ANY($1::uuid[])`, [m.fixture_venues.map((v) => v.id)]));
    require_(missingVenues === 0, `${missingVenues} manifest venue id(s) do not exist in this database — refusing.`);
    const strayVenues = await count(c,
      `SELECT count(*) n FROM venue v
        WHERE v.id = ANY($1::uuid[])
          AND NOT (v.name = ANY($2::text[]))`,
      [m.fixture_venues.map((v) => v.id), m.fixture_venues.map((v) => v.name)]);
    require_(strayVenues === 0, `${strayVenues} manifest venue id(s) no longer carry their recorded name — refusing.`);
    // Existence first, then membership. Checking only membership let a NONEXISTENT id pass (it
    // matches no row, so it is not "stray") and surface later as a raw Postgres FK error instead
    // of a readable refusal. Fails safe either way, but the diagnostic was poor.
    const missingSeries = m.target_series_ids.length - (await count(c,
      `SELECT count(*) n FROM activity_series WHERE id = ANY($1::uuid[])`, [m.target_series_ids]));
    require_(missingSeries === 0, `${missingSeries} manifest series id(s) do not exist in this database — refusing.`);
    const straySeries = await count(c,
      `SELECT count(*) n FROM activity_series WHERE id = ANY($1::uuid[]) AND NOT (source_id = ANY($2::uuid[]))`,
      [m.target_series_ids, targetIds]);
    require_(straySeries === 0, `${straySeries} manifest series id(s) do not belong to a target source — refusing.`);
    const missingOcc = m.target_occurrence_ids.length - (await count(c,
      `SELECT count(*) n FROM activity_occurrence WHERE id = ANY($1::uuid[])`, [m.target_occurrence_ids]));
    require_(missingOcc === 0, `${missingOcc} manifest occurrence id(s) do not exist in this database — refusing.`);
    const strayOcc = await count(c,
      `SELECT count(*) n FROM activity_occurrence WHERE id = ANY($1::uuid[]) AND NOT (series_id = ANY($2::uuid[]))`,
      [m.target_occurrence_ids, m.target_series_ids]);
    require_(strayOcc === 0, `${strayOcc} manifest occurrence id(s) do not belong to a target series — refusing.`);
    log(`✔ dependent ids verified: ${m.target_series_ids.length} series, ${m.target_occurrence_ids.length} occurrences, ${m.fixture_venues.length} venues all still hang off the fixture graph`);

    // ── 2. Containment boundary. No target row may carry an Operator-archived occurrence.
    const trespass = await count(c,
      `SELECT count(*) n FROM activity_occurrence o JOIN activity_series ser ON ser.id = o.series_id
        WHERE ser.source_id = ANY($1::uuid[]) AND o.archived_at >= $2`, [targetIds, m.containment_archived_at_floor]);
    require_(trespass === 0, `${trespass} target occurrence(s) were archived by the Operator — those are contained and out of scope. Refusing.`);
    const leaveAlone = await count(c, `SELECT count(*) n FROM source WHERE id = ANY($1::uuid[])`, [m.leave_alone_source_ids]);
    log(`✔ containment respected: ${leaveAlone} Operator-contained source rows present and untouched`);

    // ── 3. Global preconditions. If the wider database has moved, stop and re-derive.
    // Every precondition the MANIFEST declares is checked — not a locally-chosen subset. The first
    // version iterated only the four keys it computed itself, so venues_total and admin_users_total
    // were declared in the manifest and silently never verified, including on the
    // --include-admin-fixtures path that deletes admin_user rows. Driving the loop from the
    // manifest means declaring an expectation is the same act as enforcing it.
    const PRECONDITION_SQL: Record<string, { sql: string; params?: unknown[] }> = {
      sources_total: { sql: 'SELECT count(*) n FROM source' },
      sources_outside_window: {
        sql: `SELECT count(*) n FROM source WHERE created_at < $1 OR created_at > $2`,
        params: [m.window.from, m.window.to],
      },
      occ_total: { sql: 'SELECT count(*) n FROM activity_occurrence' },
      occ_stale: { sql: `SELECT count(*) n FROM activity_occurrence WHERE status_state='stale'` },
      venues_total: { sql: 'SELECT count(*) n FROM venue' },
      admin_users_total: { sql: 'SELECT count(*) n FROM admin_user' },
    };
    const pre: Record<string, number> = {};
    for (const [k, want] of Object.entries(m.expected_preconditions)) {
      const q = PRECONDITION_SQL[k];
      require_(!!q, `manifest declares precondition "${k}" but this script has no query for it — refusing rather than skipping it silently.`);
      pre[k] = await count(c, q!.sql, q!.params ?? []);
      require_(want === pre[k], `precondition ${k}: manifest expected ${want}, database has ${pre[k]} — refusing (re-generate the manifest)`);
    }
    log(`✔ preconditions match: ${pre.sources_total} sources (${pre.sources_outside_window} real, outside the window), ${pre.occ_total} occurrences, ${pre.occ_stale} stale`);

    // ── 4. Delete, innermost FK first. Every statement is scoped to manifest ids only.
    const occIds = m.target_occurrence_ids;
    const serIds = m.target_series_ids;
    const del = async (label: string, sql: string, params: unknown[]) => {
      const r = await c.query(sql, params);
      log(`   ${String(r.rowCount).padStart(6)}  ${label}`);
      return r.rowCount ?? 0;
    };
    log('\n── deletions ──');
    const removed: Record<string, number> = {};
    removed.sms_click_event = await del('sms_click_event', `DELETE FROM sms_click_event WHERE occurrence_id = ANY($1::uuid[])`, [occIds]);
    removed.analytics_event = await del('analytics_event', `DELETE FROM analytics_event WHERE occurrence_id = ANY($1::uuid[]) OR source_id = ANY($2::uuid[])`, [occIds, targetIds]);
    removed.correction_report = await del('correction_report', `DELETE FROM correction_report WHERE occurrence_id = ANY($1::uuid[])`, [occIds]);
    removed.provenance = await del('provenance', `DELETE FROM provenance WHERE occurrence_id = ANY($1::uuid[])`, [occIds]);
    removed.occurrence_age = await del('occurrence_age', `DELETE FROM occurrence_age WHERE occurrence_id = ANY($1::uuid[])`, [occIds]);
    removed.occurrence_category_tag = await del('occurrence_category_tag', `DELETE FROM occurrence_category_tag WHERE occurrence_id = ANY($1::uuid[])`, [occIds]);
    removed.activity_occurrence = await del('activity_occurrence', `DELETE FROM activity_occurrence WHERE id = ANY($1::uuid[])`, [occIds]);
    removed.activity_series = await del('activity_series', `DELETE FROM activity_series WHERE id = ANY($1::uuid[])`, [serIds]);
    removed.source_check_run = await del('source_check_run', `DELETE FROM source_check_run WHERE source_id = ANY($1::uuid[])`, [targetIds]);
    removed.job_queue = await del('job_queue', `DELETE FROM job_queue WHERE source_id = ANY($1::uuid[])`, [targetIds]);
    removed.source = await del('source', `DELETE FROM source WHERE id = ANY($1::uuid[])`, [targetIds]);

    if (args.includeVenues) {
      // ═══ WHY THIS IS A SUBSET DELETE AND NOT ALL 11 ═══
      // Found by rehearsing this script against a local replica of production: 4 of the 11
      // fixture venues are still referenced by series belonging to the ELEVEN Operator-contained
      // sources, which this script deliberately leaves in place. Deleting those venues would
      // either violate the FK or orphan rows the Operator is still holding open for review.
      // So: delete only the fixture venues nothing references any more, and NAME the ones left
      // behind plus the reason, so the remainder is a known follow-up rather than a silent skip.
      const vIds = m.fixture_venues.map((v) => v.id);
      const stillUsed = (await c.query<{ id: string; n: string }>(
        `SELECT v.id::text, count(ser.id) n FROM venue v
           LEFT JOIN activity_series ser ON ser.venue_id = v.id
          WHERE v.id = ANY($1::uuid[]) GROUP BY v.id HAVING count(ser.id) > 0`, [vIds]
      )).rows;
      const blocked = new Set(stillUsed.map((r) => r.id));
      const deletable = vIds.filter((id) => !blocked.has(id));
      removed.venue = await del('venue (fixture, unreferenced)', `DELETE FROM venue WHERE id = ANY($1::uuid[])`, [deletable]);
      if (blocked.size > 0) {
        log(`   ${String(blocked.size).padStart(6)}  venue KEPT — still referenced by a surviving (Operator-contained) series:`);
        for (const r of stillUsed) {
          const v = m.fixture_venues.find((x) => x.id === r.id);
          log(`           · ${r.id}  "${v?.name ?? '?'}"  (${r.n} series)`);
        }
        log('           these become deletable once the Operator closes out the contained sources.');
      }
      // Belt-and-braces: nothing we deleted may have left a dangling reference behind.
      const dangling = await count(c,
        `SELECT count(*) n FROM activity_series ser LEFT JOIN venue v ON v.id = ser.venue_id
          WHERE ser.venue_id IS NOT NULL AND v.id IS NULL`);
      require_(dangling === 0, `${dangling} series now reference a deleted venue. Rolling back.`);
    } else log('   (skipped) venue');

    if (args.includeAdminFixtures) {
      // The two orphan admin grants: user_profile rows with NO auth.users row, created in the
      // window. Re-verified here rather than trusted, because "is a real person" is the one thing
      // this script must never get wrong.
      const ids = m.orphan_profile_ids;
      const realPeople = await count(c, `SELECT count(*) n FROM auth.users WHERE id = ANY($1::uuid[])`, [ids]);
      require_(realPeople === 0, `${realPeople} of the orphan profile ids now has an auth.users row — that is a REAL account. Refusing.`);
      removed.admin_audit_log = await del('admin_audit_log', `DELETE FROM admin_audit_log WHERE admin_user_id = ANY($1::uuid[])`, [ids]);
      removed.admin_user = await del('admin_user', `DELETE FROM admin_user WHERE user_id = ANY($1::uuid[])`, [ids]);
      removed.user_profile = await del('user_profile', `DELETE FROM user_profile WHERE id = ANY($1::uuid[])`, [ids]);
    } else log('   (skipped) admin_user / user_profile / admin_audit_log — pass --include-admin-fixtures');

    // ── 5. Post-assertions. The blast radius must be exactly what was planned.
    const post = {
      sources_total: await count(c, 'SELECT count(*) n FROM source'),
      sources_outside_window: await count(c, `SELECT count(*) n FROM source WHERE created_at < $1 OR created_at > $2`, [m.window.from, m.window.to]),
      occ_total: await count(c, 'SELECT count(*) n FROM activity_occurrence'),
      occ_stale: await count(c, `SELECT count(*) n FROM activity_occurrence WHERE status_state='stale'`),
    };
    // The manifest DECLARES expected_dependent_counts for nine tables; the first version never read
    // them, so the dependent deletes were printed but not bounded — the "blast radius is exactly
    // what was planned" guarantee was not actually enforced for those tables. It is now.
    // An UNRECOGNISED key must refuse, not be skipped. The first version's `continue` meant a
    // renamed or misspelled table key silently dropped its own assertion, and the script then
    // exited 0 claiming success while an unbounded delete had actually run — the identical bug
    // class already fixed one loop earlier for expected_preconditions. A reviewer proved it by
    // renaming a key. The only legitimate reason a declared table is absent from `removed` is an
    // opt-in section that did not run this invocation, so that is enumerated explicitly rather
    // than inferred from absence.
    const OPTIONAL_TABLES = new Set(['admin_audit_log', 'admin_user', 'user_profile']); // --include-admin-fixtures
    for (const [table, want] of Object.entries(m.expected_dependent_counts)) {
      if (!(table in removed)) {
        require_(
          OPTIONAL_TABLES.has(table) && !args.includeAdminFixtures,
          `manifest declares expected_dependent_counts["${table}"] but this run deleted nothing ` +
            `from that table and it is not one of the opt-in tables. Either the key is misspelled ` +
            `or a delete is missing — refusing rather than skipping the assertion silently.`
        );
        continue;
      }
      require_(removed[table] === want,
        `dependent table ${table}: deleted ${removed[table]}, manifest expected ${want}. ` +
          `Blast radius differs from the plan — rolling back.`);
    }
    log(`✔ dependent deletes matched the manifest for ${Object.keys(m.expected_dependent_counts).filter((t) => t in removed).length} tables`);

    require_(post.sources_outside_window === pre.sources_outside_window,
      `REAL sources changed: ${pre.sources_outside_window} → ${post.sources_outside_window}. Rolling back.`);
    require_(post.sources_total === pre.sources_total - targetIds.length,
      `source count moved by ${pre.sources_total - post.sources_total}, expected exactly ${targetIds.length}. Rolling back.`);
    require_(post.occ_total === pre.occ_total - occIds.length,
      `occurrence count moved by ${pre.occ_total - post.occ_total}, expected exactly ${occIds.length}. Rolling back.`);
    require_(post.occ_stale === pre.occ_stale,
      `the 'stale' population changed (${pre.occ_stale} → ${post.occ_stale}). This script must not touch it. Rolling back.`);
    const remaining = await count(c, `SELECT count(*) n FROM source WHERE id = ANY($1::uuid[])`, [targetIds]);
    require_(remaining === 0, `${remaining} target sources survived the delete. Rolling back.`);
    const stillContained = await count(c, `SELECT count(*) n FROM source WHERE id = ANY($1::uuid[])`, [m.leave_alone_source_ids]);
    require_(stillContained === m.leave_alone_source_ids.length,
      `Operator-contained rows were affected (${m.leave_alone_source_ids.length} → ${stillContained}). Rolling back.`);

    log('\n── verification ──');
    log(`✔ real sources unchanged: ${post.sources_outside_window}`);
    log(`✔ sources ${pre.sources_total} → ${post.sources_total} (−${targetIds.length}, all manifest ids gone)`);
    log(`✔ occurrences ${pre.occ_total} → ${post.occ_total} (−${occIds.length})`);
    log(`✔ 'stale' population untouched: ${post.occ_stale}`);
    log(`✔ Operator-contained rows intact: ${stillContained}`);
    log(`\ntotal rows removed: ${Object.values(removed).reduce((a, b) => a + b, 0)}`);

    if (args.commit && args.confirmed) {
      await c.query('COMMIT');
      committed = true;
      log('\n★ COMMITTED.');
    } else {
      await c.query('ROLLBACK');
      log(`\n● ROLLED BACK — nothing was changed. The counts above are from a real execution.`);
      if (args.commit !== args.confirmed) {
        // Exit 3, not 0: a HALF-confirmation means someone meant to write and did not. Inside a
        // wrapper script an exit 0 there reads as "done", which is the worst possible reading.
        log('  (both --commit AND --yes-write-production are required to commit — exiting 3)');
        c.release();
        await pool.end();
        process.exit(3);
      }
    }
  } catch (err) {
    if (!committed) await c.query('ROLLBACK').catch(() => {});
    const msg = err instanceof Abort ? `ABORTED: ${err.message}` : `FAILED: ${(err as Error).message}`;
    log(`\n✖ ${msg}\n  Transaction rolled back; the database is unchanged.`);
    c.release(); await pool.end();
    process.exit(1);
  }
  c.release();
  await pool.end();
}

void main();
