// Static fixture activities for the mobile shell — East Vancouver, week of 2026-07-13.
// Fixture-only: no database, no network, no secrets. Source URLs are public,
// authoritative pages a parent would deep-link to for booking/verification.
// Shaped to TSD §6 `activity_occurrence` so this swaps to the real API cleanly.

import type { Activity } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: 'trout-lake-public-skate',
    activityName: 'Public skate',
    venue: 'Trout Lake Rink',
    area: 'Trout Lake',
    driveMinutes: 12,
    distanceKm: 4.1,
    category: 'skate',
    ageMin: 5,
    ageMax: 12,
    startIso: '2026-07-18T14:00:00-07:00',
    endIso: '2026-07-18T16:00:00-07:00',
    timeOfDay: 'afternoon',
    costStatus: 'known',
    costMinCad: 7,
    status: 'confirmed',
    booking: 'drop_in',
    confidence: 'official',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/trout-lake-community-centre.aspx',
    locationUrl: 'https://maps.google.com/?q=Trout+Lake+Community+Centre+Vancouver',
    lastCheckedIso: '2026-07-13T07:30:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: true,
    descriptionSnippet: 'Open ice for families. Helmets recommended for kids; skate rentals on site.',
    parentNotes: ['Stroller parking inside', 'Sibling-friendly — all ages skate together', 'On the 20 bus line'],
  },
  {
    id: 'templeton-family-swim',
    activityName: 'Family swim',
    venue: 'Templeton Pool',
    area: 'Hastings-Sunrise',
    driveMinutes: 8,
    distanceKm: 2.3,
    category: 'swim',
    ageMin: 0,
    ageMax: 12,
    startIso: '2026-07-19T10:00:00-07:00',
    endIso: '2026-07-19T11:30:00-07:00',
    timeOfDay: 'morning',
    costStatus: 'known',
    costMinCad: 3,
    costMaxCad: 4,
    status: 'bookable_open',
    booking: 'bookable_now',
    confidence: 'official',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/templeton-pool.aspx',
    bookingUrl: 'https://vancouver.ca/parks-recreation-culture/register-for-a-drop-in.aspx',
    locationUrl: 'https://maps.google.com/?q=Templeton+Pool+Vancouver',
    lastCheckedIso: '2026-07-13T06:50:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: false,
    descriptionSnippet: 'Warm shallow end suits toddlers; lifeguards on deck. Book a slot to guarantee entry.',
    parentNotes: ['Family change rooms', 'Toddler life jackets available', 'Parking limited — transit easier'],
  },
  {
    id: 'britannia-toddler-storytime',
    activityName: 'Toddler storytime',
    venue: 'Britannia Branch, Vancouver Public Library',
    area: 'Grandview-Woodland',
    driveMinutes: 6,
    distanceKm: 1.6,
    category: 'storytime',
    ageMin: 0,
    ageMax: 3,
    startIso: '2026-07-13T10:30:00-07:00',
    endIso: '2026-07-13T11:00:00-07:00',
    timeOfDay: 'morning',
    costStatus: 'free',
    status: 'confirmed',
    booking: 'drop_in',
    confidence: 'official',
    sourceName: 'vpl.ca',
    sourceUrl: 'https://www.vpl.ca/program/family-storytime',
    locationUrl: 'https://maps.google.com/?q=Britannia+Library+Vancouver',
    lastCheckedIso: '2026-07-12T16:00:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: true,
    descriptionSnippet: 'Songs, rhymes and picture books for the littlest listeners. No registration — just arrive.',
    parentNotes: ['Stroller space at the back', 'Quiet room next door for meltdowns', 'Low-sensory friendly'],
  },
  {
    id: 'renfrew-open-gym',
    activityName: 'Family open gym',
    venue: 'Renfrew Community Centre',
    area: 'Renfrew-Collingwood',
    driveMinutes: 15,
    distanceKm: 5.4,
    category: 'open_gym',
    ageMin: 0,
    ageMax: 6,
    startIso: '2026-07-14T09:30:00-07:00',
    endIso: '2026-07-14T11:00:00-07:00',
    timeOfDay: 'morning',
    costStatus: 'known',
    costMinCad: 2,
    costMaxCad: 3,
    status: 'confirmed',
    booking: 'drop_in',
    confidence: 'official',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/renfrew-community-centre.aspx',
    locationUrl: 'https://maps.google.com/?q=Renfrew+Community+Centre+Vancouver',
    lastCheckedIso: '2026-07-13T07:00:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: true,
    descriptionSnippet: 'Ride-on toys, mats and balls in the gym. Runs whatever the weather.',
    parentNotes: ['Great rainy-morning burn-off', 'Coffee in the lobby', 'Free parking on site'],
  },
  {
    id: 'stanley-park-mini-train',
    activityName: 'Miniature train ride',
    venue: 'Stanley Park Miniature Train',
    area: 'Stanley Park',
    driveMinutes: 22,
    distanceKm: 8.9,
    category: 'festival',
    ageMin: 2,
    ageMax: 12,
    startIso: '2026-07-18T11:00:00-07:00',
    endIso: '2026-07-18T16:00:00-07:00',
    timeOfDay: 'afternoon',
    costStatus: 'known',
    costMinCad: 6,
    status: 'bookable_open',
    booking: 'registration',
    confidence: 'official',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/stanley-park-train.aspx',
    bookingUrl: 'https://vancouver.ca/parks-recreation-culture/stanley-park-train-tickets.aspx',
    locationUrl: 'https://maps.google.com/?q=Stanley+Park+Miniature+Train',
    lastCheckedIso: '2026-07-11T09:00:00-07:00',
    indoor: false,
    rainyDay: false,
    dropIn: false,
    descriptionSnippet: 'A 15-minute ride through the forest. Timed tickets — book ahead on summer weekends.',
    parentNotes: ['Stroller parking at the station', 'Toddlers ride free on a lap', 'Shaded picnic tables nearby'],
  },
  {
    id: 'everett-crowley-nature',
    activityName: 'Family nature walk',
    venue: 'Everett Crowley Park',
    area: 'Champlain Heights',
    driveMinutes: 17,
    distanceKm: 6.2,
    category: 'nature',
    ageMin: 5,
    ageMax: 12,
    startIso: '2026-07-19T13:00:00-07:00',
    endIso: '2026-07-19T15:00:00-07:00',
    timeOfDay: 'afternoon',
    costStatus: 'free',
    status: 'confirmed',
    booking: 'drop_in',
    confidence: 'editorial',
    sourceName: 'metrovancouver.org',
    sourceUrl: 'https://metrovancouver.org/services/regional-parks',
    locationUrl: 'https://maps.google.com/?q=Everett+Crowley+Park',
    lastCheckedIso: '2026-07-10T12:00:00-07:00',
    indoor: false,
    rainyDay: false,
    dropIn: true,
    descriptionSnippet: 'Guided loop with a park steward — pond dipping and berry spotting for school-age kids.',
    parentNotes: ['Not stroller-friendly (dirt trails)', 'Wear closed shoes', 'Washrooms at the main entrance'],
  },
  {
    id: 'science-world-tinker',
    activityName: 'Tinkering studio',
    venue: 'Science World',
    area: 'False Creek',
    driveMinutes: 12,
    distanceKm: 3.8,
    category: 'museum_arts',
    ageMin: 3,
    ageMax: 12,
    startIso: '2026-07-15T10:00:00-07:00',
    endIso: '2026-07-15T17:00:00-07:00',
    timeOfDay: 'afternoon',
    costStatus: 'known',
    costMinCad: 22,
    costMaxCad: 30,
    status: 'bookable_open',
    booking: 'bookable_now',
    confidence: 'official',
    sourceName: 'scienceworld.ca',
    sourceUrl: 'https://www.scienceworld.ca/visit/',
    bookingUrl: 'https://www.scienceworld.ca/tickets/',
    locationUrl: 'https://maps.google.com/?q=Science+World+Vancouver',
    lastCheckedIso: '2026-07-13T06:30:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: false,
    descriptionSnippet: 'Hands-on build stations inside the galleries. Timed entry — buy ahead on rainy days.',
    parentNotes: ['Fully indoor', 'Stroller-accessible', 'On the SkyTrain (Main St–Science World)'],
  },
  {
    id: 'killarney-skate-lessons',
    activityName: 'Learn-to-skate lessons',
    venue: 'Killarney Community Centre',
    area: 'Killarney',
    driveMinutes: 20,
    distanceKm: 9.1,
    category: 'skate',
    ageMin: 5,
    ageMax: 12,
    startIso: '2026-07-15T16:00:00-07:00',
    endIso: '2026-07-15T17:00:00-07:00',
    timeOfDay: 'evening',
    costStatus: 'known',
    costMinCad: 78,
    status: 'confirmed',
    booking: 'registration',
    confidence: 'official',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/killarney-community-centre.aspx',
    bookingUrl: 'https://ca.apm.activecommunities.com/vancouver',
    locationUrl: 'https://maps.google.com/?q=Killarney+Community+Centre+Vancouver',
    lastCheckedIso: '2026-07-13T07:15:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: false,
    descriptionSnippet: 'Six-week beginner series. Register for the whole set — spots go fast.',
    parentNotes: ['Bring your own helmet', 'Viewing benches rinkside', 'Free parking'],
  },
  {
    id: 'kits-indoor-play',
    activityName: 'Indoor playground',
    venue: 'Kitsilano Indoor Play',
    area: 'Kitsilano',
    driveMinutes: 28,
    distanceKm: 14.2,
    category: 'indoor_play',
    ageMin: 0,
    ageMax: 5,
    startIso: '2026-07-14T09:00:00-07:00',
    endIso: '2026-07-14T12:00:00-07:00',
    timeOfDay: 'morning',
    costStatus: 'known',
    costMinCad: 12,
    status: 'bookable_open',
    booking: 'bookable_now',
    confidence: 'editorial',
    sourceName: 'kitsplay.example.ca',
    sourceUrl: 'https://example.ca/kitsilano-indoor-play',
    bookingUrl: 'https://example.ca/kitsilano-indoor-play/book',
    locationUrl: 'https://maps.google.com/?q=Kitsilano+Vancouver',
    lastCheckedIso: '2026-07-12T10:00:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: false,
    descriptionSnippet: 'Soft-play structure and toddler zone. Socks required for everyone.',
    parentNotes: ['Under-5 only', 'Café for parents', 'Farther out — 20 km band'],
  },
  {
    id: 'trout-lake-farmers-market',
    activityName: 'Kids corner — farmers market',
    venue: 'Trout Lake Farmers Market',
    area: 'Trout Lake',
    driveMinutes: 12,
    distanceKm: 4.0,
    category: 'festival',
    ageMin: 0,
    ageMax: 12,
    startIso: '2026-07-18T09:00:00-07:00',
    endIso: '2026-07-18T14:00:00-07:00',
    timeOfDay: 'morning',
    costStatus: 'free',
    status: 'stale',
    booking: 'drop_in',
    confidence: 'editorial',
    sourceName: 'eatlocal.org',
    sourceUrl: 'https://eatlocal.org/markets/trout-lake',
    locationUrl: 'https://maps.google.com/?q=Trout+Lake+Vancouver',
    lastCheckedIso: '2026-07-07T09:00:00-07:00',
    indoor: false,
    rainyDay: false,
    dropIn: true,
    descriptionSnippet: 'Face painting and a craft table by the entrance. Confirm the craft schedule on the day.',
    parentNotes: ['Cash for treats', 'Stroller-friendly grass', 'Shade is limited midday'],
  },
  {
    id: 'new-brighton-outdoor-pool',
    activityName: 'Outdoor pool session',
    venue: 'New Brighton Pool',
    area: 'Hastings-Sunrise',
    driveMinutes: 10,
    distanceKm: 3.1,
    category: 'swim',
    ageMin: 0,
    ageMax: 99,
    startIso: '2026-07-20T12:00:00-07:00',
    endIso: '2026-07-20T18:00:00-07:00',
    timeOfDay: 'afternoon',
    costStatus: 'unknown',
    status: 'schedule_not_published',
    booking: 'none',
    confidence: 'candidate',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/new-brighton-pool.aspx',
    locationUrl: 'https://maps.google.com/?q=New+Brighton+Pool+Vancouver',
    lastCheckedIso: '2026-07-13T06:40:00-07:00',
    indoor: false,
    rainyDay: false,
    dropIn: false,
    descriptionSnippet: 'Saltwater pool by the water. Summer hours usually post 1–2 weeks ahead.',
    parentNotes: ['Waterfront views', 'Bring sunscreen', 'Schedule not confirmed yet'],
  },
  {
    id: 'qe-park-toboggan',
    activityName: 'Toboggan hill',
    venue: 'Queen Elizabeth Park',
    area: 'Riley Park',
    driveMinutes: 19,
    distanceKm: 7.7,
    category: 'nature',
    ageMin: 3,
    ageMax: 12,
    startIso: '2026-12-20T10:00:00-08:00',
    endIso: '2026-12-20T16:00:00-08:00',
    timeOfDay: 'afternoon',
    costStatus: 'free',
    status: 'seasonal_out_of_season',
    booking: 'none',
    confidence: 'editorial',
    sourceName: 'vancouver.ca',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/queen-elizabeth-park.aspx',
    locationUrl: 'https://maps.google.com/?q=Queen+Elizabeth+Park+Vancouver',
    lastCheckedIso: '2026-07-13T06:20:00-07:00',
    seasonLabel: 'December',
    indoor: false,
    rainyDay: false,
    dropIn: true,
    descriptionSnippet: 'A neighbourhood favourite once the snow arrives. Listed here so you can plan ahead.',
    parentNotes: ['Winter only', 'Bring a sled', 'Steep for toddlers — school-age is safer'],
  },
  {
    id: 'roundhouse-family-dance',
    activityName: 'Family dance session',
    venue: 'Roundhouse Community Centre',
    area: 'Yaletown',
    driveMinutes: 16,
    distanceKm: 6.9,
    category: 'museum_arts',
    ageMin: 3,
    ageMax: 8,
    startIso: '2026-07-17T17:00:00-07:00',
    endIso: '2026-07-17T18:00:00-07:00',
    timeOfDay: 'evening',
    costStatus: 'known',
    costMinCad: 5,
    status: 'cancelled',
    booking: 'none',
    confidence: 'official',
    sourceName: 'roundhouse.ca',
    sourceUrl: 'https://roundhouse.ca/programs/',
    locationUrl: 'https://maps.google.com/?q=Roundhouse+Community+Centre+Vancouver',
    lastCheckedIso: '2026-07-13T06:10:00-07:00',
    indoor: true,
    rainyDay: true,
    dropIn: false,
    descriptionSnippet: 'This Friday session was cancelled by the venue. Weekly series resumes next month.',
    parentNotes: ['Cancelled — do not travel', 'Check back for August dates'],
  },
];

export function findActivity(id: string): Activity | undefined {
  return ACTIVITIES.find((a) => a.id === id);
}
