-- 0029_stale_occurrence_flip_schedule.sql — schedule the OCCURRENCE-level staleness flip
-- on the durable global-job scheduler. SHIPPED DISABLED.
--
-- WHY THIS EXISTS. Migration 0028 built a schedule, a run ledger, a DB-enforced exactly-once
-- lock, a circuit breaker, missed-run detection and abandoned-run reconciliation — and had
-- exactly ONE configured job (`corrections_retention`), itself disabled. A scheduler with no
-- live tenant is a scheduler nobody has proved anything about. This adds a second tenant that
-- was NOT written for the scheduler and therefore actually tests its shape.
--
-- WHAT THE JOB IS. `stale_occurrence_flip` → worker/core/stale-occurrence-flip.ts, which calls
-- worker/health/stale.ts flipStaleOccurrences(). That function has existed since G-T15-4 with
-- NO RUNTIME CALLER AT ALL: outside tests/health/stale.test.ts nothing in the repo invoked it,
-- so occurrence-level staleness has never once been applied to a row. (Measured at
-- aa14057ea37cc57c68bf0338cb6c484f81a2b229 by a repo-wide grep excluding node_modules; the
-- only non-test hits were its own definition and a comment in vitest.workspace.ts.)
--
-- ── BLAST RADIUS. READ THIS BEFORE ENABLING. ────────────────────────────────────────────────
-- The statement is an UPDATE over activity_occurrence scoped by PREDICATE — not by batch, not
-- by time window, and not by any particular source id. It DOES exclude one CLASS of source
-- (operator-fed; see below), but there is no id list and no LIMIT: every run can touch every
-- row that satisfies:
--     archived_at IS NULL
--   AND last_checked_at IS NOT NULL
--   AND status_state ∈ STALE_DEMOTE_FROM   (the six "live" states in worker/health/stale.ts;
--                                           human/terminal and already-low states are excluded
--                                           so staleness never overwrites a specific decision)
--   AND source.ingestion_method ∉ STALE_FLIP_EXCLUDED_INGESTION_METHODS   (= {'manual'})
--   AND last_checked_at < now() - STALE_CADENCE_GRACE × COALESCE(near_date_cadence,
--                                                                baseline_cadence)
-- source.baseline_cadence is NOT NULL DEFAULT '1 day' (migration 0003), so the effective
-- threshold for a source that has never had a cadence configured is 2 days.
--
-- The effect on a flipped row is a DEMOTION, not a deletion and not a hide — but "demotion"
-- understates what a parent actually sees, so here it is exactly, measured at
-- 23466ad2ff6fc5766dd874507069ab6f349c3f5d:
--
--   RANK. lib/search/rank.ts scores 'stale' 0.15 — the lowest of any SHOWN status, not the
--   lowest of any status. Three score lower (suspended 0.1, needs_review 0.1, cancelled 0.05)
--   and those three are exactly the ones lib/search/filters/status.ts classes 'hidden', so
--   they never reach a parent at all. Among everything that IS shown, 'stale' is last.
--
--   VISIBILITY. Still shown. 'stale' is not in HIDDEN_STATUSES, so the repository returns it
--   and the search response carries it.
--
--   SECTION — the part the word "demotion" hides. app/search/page.tsx does not keep the
--   primary/expected split the search response arrives with: it merges `results` and
--   `expected` (mapSearchResponseToActivities) and re-partitions the whole set with
--   partitionSections (app/preview/_data/filter.ts), which asks statusMeta
--   (app/preview/_data/format.ts) for a section — and statusMeta puts ONLY 'confirmed' and
--   'bookable_open' in the confirmed section. So a row flipped FROM one of those two LEAVES
--   the confirmed list and reappears below it in the expected section, relabelled "May be
--   stale" with the copy "Last check is a few days old — may be out of date". Rows flipped
--   from the other four members of STALE_DEMOTE_FROM (not_yet_bookable,
--   schedule_not_published, inferred_recurring, seasonal_active) were already in the expected
--   section; for those the flip changes the label, the copy and the rank, but not the section.
--
--   THAT SECTION MOVE IS INTENDED DESIGN, NOT AN ARTEFACT OF THE RENDER PATH. statusMeta's
--   header states it as an honesty invariant and cites UXR-06 / T-07 / Appendix D — "never
--   show stale/expected/seasonal as confirmed" — and applies it to all 16 statuses. The
--   mechanism is doing what it was specified to do.
--
-- WHY THE PREDICATE EXEMPTS OPERATOR-FED SOURCES, AND WHAT THAT CHANGED SINCE THIS MIGRATION
-- WAS FIRST WRITTEN. The staleness rule was written for INGESTED listings, where "nothing has
-- re-checked this lately" is both true and SELF-CORRECTING: the next successful ingest restores
-- last_checked_at and status_state together (worker/core/upsert.ts), and the caveat lifts
-- itself. A hand-curated listing used to sit inside the identical rule with nothing to lift it,
-- so its caveat was permanent until a human returned to it.
--
-- >>> THAT IS NO LONGER TRUE, AND THIS PARAGRAPH IS THE CORRECTION. <<< The flip's predicate
-- now carries `AND source.ingestion_method <> 'manual'`
-- (STALE_FLIP_EXCLUDED_INGESTION_METHODS in worker/health/stale.ts). Occurrences under an
-- operator-fed source are NOT demoted, at any age. Earlier revisions of this header told the
-- person flipping `enabled` that hand-curated listings WOULD be demoted with no automatic
-- recovery, and told them to expect a large family='manual' row in the dry run below. Both
-- statements were accurate when written and are now false; the dry-run query has been
-- corrected to match, and it can no longer return a manual row at all.
--
-- WHY `ingestion_method` AND NOT `authority_tier`, since both columns have a 'manual' value and
-- app/admin/listings/_lib/data.ts's getOrCreateManualSource sets BOTH (plus family='manual') on
-- the one canonical row: `authority_tier` is a TRUST claim about the data and gates no fetching
-- at all, whereas `ingestion_method` is the column that decides whether anything ever fetches
-- the source again AUTOMATICALLY — it is the exact column worker/scheduler/tiered.ts's candidate
-- predicate uses to refuse to enqueue. (Earlier revisions of this header said "source family
-- 'manual'". That was loose language for ingestion_method, not a third rule.)
--
-- >>> READ "AUTOMATICALLY" LITERALLY — AN EARLIER REVISION OF THIS PARAGRAPH OVERSTATED THE
-- TRAP. <<< A manual source is not unreachable; it is only unreachable UNATTENDED.
-- worker/src/ingest-once.ts selects a source by --source-id or --family/--name with NO
-- ingestion_method filter, so an operator CAN deliberately re-ingest a manual source from the
-- CLI, and that run does lift the caveat (it reaches worker/core/upsert.ts, which re-stamps
-- last_checked_at and status_state together). What manual listings have no path back from is
-- UNATTENDED recovery — which is the whole of the problem, since the caveat would otherwise be
-- applied by a scheduled job and lifted only by a human who knew to go looking.
--
-- AND THE REASON THIS EXCLUSION CANNOT OVER-PROTECT, which is stronger than any row count:
-- over-protecting would require a source that is 'manual' AND still automatically re-checked.
-- No such source can exist, because ONE COLUMN GATES BOTH — the set excluded here is exactly
-- the set tiered.ts refuses to enqueue. The exemption cannot strand a source that the scheduler
-- would otherwise have kept fresh.
--
-- Neither running nor not running this job destroys data. The failure mode of running it is
-- "INGESTED listings whose source went quiet get caveated and pushed below the confirmed list",
-- which is the intended behaviour; the failure mode of NOT running it is "listings nobody has
-- re-checked keep presenting as confirmed", which is the honesty invariant above being quietly
-- false. The hand-curated-collateral failure mode that used to sit on the "running it" side of
-- that trade is now excluded by the predicate rather than reserved by the flag.
--
-- WHAT THE EXEMPTION COSTS, STATED PLAINLY SO THE FLAG-FLIPPER OWNS IT: a hand-curated listing
-- that has genuinely gone out of date will now keep presenting as 'confirmed' indefinitely.
-- The exemption does not make manual listings fresh — it makes this job silent about them, and
-- moves that problem to whatever surfaces manual curation for human review.
--
-- ROUTES OUT OF 'stale', re-derived at this file's revision rather than carried forward: a
-- demoted row is restored only by a write that re-stamps status_state — worker/core/upsert.ts
-- on a real re-ingest (reachable for a MANUAL source too, via a deliberate
-- worker/src/ingest-once.ts CLI run; what manual sources lack is the AUTOMATIC trigger, not the
-- write), the admin QA queue's approve (app/admin/qa-queue/_lib/data.ts), or
-- resolving a correction (app/admin/corrections/_lib/data.ts). One more EXISTS IN THE CODE and
-- is worth knowing about precisely because it is invisible from any of those: worker/health/
-- season.ts lists 'stale' in SEASON_INHERITABLE_FROM and inheritOccurrenceStatus() would move
-- such a row to 'seasonal_active' for an in_season source. It is NOT a live path — that module
-- has no non-test importer anywhere in the repo, the same condition flipStaleOccurrences() was
-- in before this migration gave it one. Give season.ts a caller and it becomes a fourth route.
--
-- ── WHY THE PRODUCER'S SLOT-SKIPPING IS SAFE FOR THIS JOB ──────────────────────────────────
-- worker/scheduler/global-jobs.ts advances next_run_at to the first slot in the FUTURE, so an
-- outage's missed slots are DROPPED, never replayed. That is destructive for edge-triggered
-- work and correct for LEVEL-TRIGGERED work. This job is level-triggered as strongly as the
-- category allows: its predicate is a statement about the world at now(), with no reference to
-- the slot it is running for, so one run after ten missed slots selects a superset of what all
-- ten would have selected and leaves nothing behind. It is also idempotent — 'stale' is not in
-- STALE_DEMOTE_FROM, so a row it already flipped is not a candidate again.
--
-- ── CADENCE: 1 day ─────────────────────────────────────────────────────────────────────────
-- The staleness threshold is itself ≥ 2 × a source's cadence, so sub-daily polling would only
-- shorten the latency between a row crossing the threshold and being demoted — on a ranking
-- signal, not on anything time-critical. Against that, each run is an unindexed predicate over
-- the whole occurrence table joined to series and source. Daily is the cheap side of a
-- trade-off whose expensive side buys hours of latency on a ranking hint.
--
-- ── max_consecutive_failures: 3, WRITTEN EXPLICITLY ────────────────────────────────────────
-- Stated in the INSERT rather than inherited from the column DEFAULT so the choice is visible
-- in the row, and survives a future change to that default. It is chosen knowing two things
-- about this scheduler: GLOBAL_JOB_MAX_ATTEMPTS is 1 (the cadence is the retry, the breaker is
-- the failure policy), and resetGlobalJobBreaker() is deliberately not called from any runtime
-- path — so a tripped breaker STAYS tripped until a human clears it. At a daily cadence, 3
-- means one transient database fault costs a day and is absorbed, while a structural fault
-- stops the schedule within three days and asks for a person. A threshold of 1 would convert a
-- single connection blip into an indefinite silent stop that nothing pages anyone about; a
-- larger one would let a genuinely broken job keep running the same UPDATE for a week.
--
-- ── next_run_at = now() ────────────────────────────────────────────────────────────────────
-- Matching 0028. The row is disabled, so this instant is in the past by however long the flag
-- stays off; the first tick after enabling therefore enqueues immediately (which is what an
-- operator flipping the flag wants to see) and logs a large skipped-slot WARN naming every
-- daily slot that elapsed while it was disabled. For this job that warning is expected and
-- benign — see the level-triggered note above — but it is not silent, by design.

-- ── forward ──────────────────────────────────────────────────────────────────

-- enabled = FALSE, and that is the whole point. Registering the handler
-- (worker/core/job-handlers.ts) is a CAPABILITY; this flag is the ENABLEMENT, and they are
-- deliberately separate acts. Turning it on mutates real activity_occurrence rows on the
-- public search surface, with the consequence documented under BLAST RADIUS above.
INSERT INTO global_job_schedule (job_type, cadence, enabled, next_run_at, max_consecutive_failures)
VALUES ('stale_occurrence_flip', interval '1 day', false, now(), 3)
ON CONFLICT (job_type) DO NOTHING;

-- ── operator notes ───────────────────────────────────────────────────────────
-- ENABLE (a deliberate act; reversible by flipping it back, but the rows it has already
-- demoted are NOT restored by disabling it — see BLAST RADIUS):
--   UPDATE global_job_schedule SET enabled = true WHERE job_type = 'stale_occurrence_flip';
--
-- DRY RUN THE PREDICATE FIRST — how many rows the next run would touch, and where they live.
-- This is a SELECT; it changes nothing. It mirrors worker/health/stale.ts's UPDATE clause for
-- clause, INCLUDING the operator-fed exemption, so its count is what the next run would really
-- demote:
--   SELECT s.family, s.ingestion_method, s.name, count(*) AS would_flip
--     FROM activity_occurrence o
--     JOIN activity_series ser ON ser.id = o.series_id
--     JOIN source s ON s.id = ser.source_id
--    WHERE o.archived_at IS NULL
--      AND o.last_checked_at IS NOT NULL
--      AND o.status_state::text = ANY (ARRAY['confirmed','bookable_open','not_yet_bookable',
--                                            'schedule_not_published','inferred_recurring',
--                                            'seasonal_active'])
--      AND s.ingestion_method <> 'manual'
--      AND o.last_checked_at < now() - make_interval(
--            secs => extract(epoch FROM COALESCE(s.near_date_cadence, s.baseline_cadence)) * 2)
--    GROUP BY 1, 2, 3 ORDER BY would_flip DESC;
--   -- ingestion_method is SELECTed so the exemption is visible in the output rather than
--   -- implied by its absence: every row returned is non-manual BY CONSTRUCTION, and a
--   -- 'manual' row appearing here would mean the code and this query have drifted apart.
--
-- TO SEE WHAT THE EXEMPTION IS SPARING — the hand-curated listings that WOULD have been
-- demoted before it existed, i.e. the listings now carrying no staleness caveat however old
-- they are. This is the review queue the exemption creates, and it is also read-only. Run the
-- query above with the `<>` flipped to `=`:
--      ...  AND s.ingestion_method = 'manual'  ...
--
-- RESET a tripped breaker (explicit recovery; there is no automatic path) — as 0028.

-- ── rollback ────────────────────────────────────────────────────────────────
--   DELETE FROM global_job_schedule WHERE job_type = 'stale_occurrence_flip';
--   -- CASCADEs its global_job_run ledger rows. Does NOT un-flip any occurrence: nothing
--   -- records what status_state a row held before it was demoted.
